### ISSUE TITLE
Implement KeplrSigner

### ISSUE THREAD

**Issue by RiccardoM** [desmos-labs/desmjs#2]
Currently DesmJS only offers a custom implementation of the `Signer` class: `WalletConnectSigner`. Even thought this is surely useful for some cases (eg. when we want to give users the ability to log into a DApp using DPM), it's not sufficient to cover all options. 

For this reason, I think we also need to add a `KeplrSigner` class that implements the `Signer` instance and relies on [Keplr](https://github.com/chainapsis/keplr-wallet) to manage the accounts and sign the transactions. 

This implementation should then live inside its own package `keplr` that can be published at `@desmoslabs/desmjs-keplr`

**Comment by bragaz** [comment]
@RiccardoM Doing this will also allow to connect chains through keplr in mobile apps right?

**Comment by RiccardoM** [comment]
@bragaz What do you mean? I don't get the question

**Comment by bragaz** [comment]
@RiccardoM If it's possible to have an option, for instance when connecting other chains to a profile in a mobile app, that says "Connect with Keplr".

**Comment by RiccardoM** [comment]
> @RiccardoM If it's possible to have an option, for instance when connecting other chains to a profile in a mobile app, that says "Connect with Keplr".

No, this issue does not related to that. This is only related to the Keplr web extension, not its mobile version.  

What you are asking can already be done using DesmJS and a [`WalletConnectSigner`](https://github.com/desmos-labs/desmjs/blob/main/packages/walletconnect/src/signer.ts#L23) instance. Keplr Mobile is compatible with WalletConnect, so that should be sufficient to allow signing transactions (including fake ones to connect a Desmos profile to an external chain) from any DApp with it.
